Repository Team-Crops/fit-server, pull requests merged in 2023-12, with the labels that each got.

#4 [feat] Add feature Kakao OAuth, Google OAuth, Spring Security
  .gitignore
  build.gradle
  src/main/java/org/crops/fitserver/FitServerApplication.java
  src/main/java/org/crops/fitserver/auth/controller/AuthController.java
  src/main/java/org/crops/fitserver/auth/facade/AuthFacade.java
  src/main/java/org/crops/fitserver/auth/facade/dto/SocialLoginPageResponse.java
  src/main/java/org/crops/fitserver/auth/facade/dto/TokenResponse.java
  src/main/java/org/crops/fitserver/auth/facade/impl/AuthFacadeImpl.java
  src/main/java/org/crops/fitserver/auth/service/AuthService.java
  src/main/java/org/crops/fitserver/auth/service/OAuthService.java
  src/main/java/org/crops/fitserver/auth/service/impl/GoogleOAuthServiceImpl.java
  src/main/java/org/crops/fitserver/auth/service/impl/KakaoOAuthServiceImpl.java
  src/main/java/org/crops/fitserver/auth/service/provider/OAuthServiceProvider.java
  src/main/java/org/crops/fitserver/global/config/FeignConfig.java
  src/main/java/org/crops/fitserver/global/config/JpaConfig.java
  src/main/java/org/crops/fitserver/global/config/SecurityConfig.java
  src/main/java/org/crops/fitserver/global/config/WebConfig.java
  src/main/java/org/crops/fitserver/global/entity/BaseEntity.java
  src/main/java/org/crops/fitserver/global/entity/BaseTimeEntity.java
  src/main/java/org/crops/fitserver/global/exception/FitException.java
  src/main/java/org/crops/fitserver/global/exception/NotFoundException.java
  src/main/java/org/crops/fitserver/global/exception/UnauthorizedException.java
  src/main/java/org/crops/fitserver/global/feign/oauth/OAuthToken.java
  src/main/java/org/crops/fitserver/global/feign/oauth/google/GoogleAuthServerClient.java
  src/main/java/org/crops/fitserver/global/feign/oauth/google/GoogleClientProperty.java
  src/main/java/org/crops/fitserver/global/feign/oauth/google/GoogleServerClient.java
  src/main/java/org/crops/fitserver/global/feign/oauth/google/GoogleSocialUserProfile.java
  src/main/java/org/crops/fitserver/global/feign/oauth/kakao/KakaoAuthServerClient.java
  src/main/java/org/crops/fitserver/global/feign/oauth/kakao/KakaoClientProperty.java
  src/main/java/org/crops/fitserver/global/feign/oauth/kakao/KakaoServerClient.java
  src/main/java/org/crops/fitserver/global/feign/oauth/kakao/KakaoSocialUserProfile.java
  src/main/java/org/crops/fitserver/global/filter/JwtAccessDeniedHandler.java
  src/main/java/org/crops/fitserver/global/filter/JwtAuthenticationFilter.java
  src/main/java/org/crops/fitserver/global/filter/JwtExceptionFilter.java
  src/main/java/org/crops/fitserver/global/http/ErrorType.java
  src/main/java/org/crops/fitserver/global/http/FailResponse.java
  src/main/java/org/crops/fitserver/global/http/HeaderTokenExtractor.java
  src/main/java/org/crops/fitserver/global/http/HttpResponse.java
  src/main/java/org/crops/fitserver/global/http/SocailPlatformRequestConverter.java
  src/main/java/org/crops/fitserver/global/jwt/JwtProperty.java
  src/main/java/org/crops/fitserver/global/jwt/JwtProvider.java
  src/main/java/org/crops/fitserver/global/jwt/JwtResolver.java
  src/main/java/org/crops/fitserver/global/jwt/TokenCollection.java
  src/main/java/org/crops/fitserver/global/jwt/TokenInfo.java
  src/main/java/org/crops/fitserver/global/security/PrincipalDetails.java
  src/main/java/org/crops/fitserver/global/security/PrincipalDetailsService.java
  src/main/java/org/crops/fitserver/user/domain/SocialPlatform.java
  src/main/java/org/crops/fitserver/user/domain/SocialUserInfo.java
  src/main/java/org/crops/fitserver/user/domain/User.java
  src/main/java/org/crops/fitserver/user/domain/UserRole.java
  src/main/java/org/crops/fitserver/user/repository/SocialUserInfoRepository.java
  src/main/java/org/crops/fitserver/user/repository/UserRepository.java
  src/main/java/org/crops/fitserver/user/repository/UserRepositoryCustom.java
  src/main/resources/application-dev.yaml
Labels: feat

#12 [Feat] spring boot version to 3.1.5
  build.gradle
  src/main/java/org/crops/fitserver/auth/controller/AuthController.java
  src/main/java/org/crops/fitserver/global/config/SecurityConfig.java
  src/main/java/org/crops/fitserver/global/entity/BaseEntity.java
  src/main/java/org/crops/fitserver/global/entity/BaseTimeEntity.java
  src/main/java/org/crops/fitserver/global/filter/JwtAccessDeniedHandler.java
  src/main/java/org/crops/fitserver/global/filter/JwtAuthenticationFilter.java
  src/main/java/org/crops/fitserver/global/filter/JwtExceptionFilter.java
  src/main/java/org/crops/fitserver/global/http/HeaderTokenExtractor.java
  src/main/java/org/crops/fitserver/global/jwt/JwtProvider.java
  src/main/java/org/crops/fitserver/global/jwt/JwtResolver.java
  src/main/java/org/crops/fitserver/global/log/LogFilter.java
  src/main/java/org/crops/fitserver/global/log/LogRequestFilter.java
  src/main/java/org/crops/fitserver/user/domain/SocialUserInfo.java
  src/main/java/org/crops/fitserver/user/domain/User.java
  src/test/java/org/crops/fitserver/FitServerApplicationTests.java
  src/test/java/org/crops/fitserver/controller/SampleControllerTest.java
Labels: enhancement

#13 [fix] error fix security, open feign
  .github/workflows/cd_dev.yml
  build.gradle
  src/main/java/org/crops/fitserver/FitServerApplication.java
  src/main/java/org/crops/fitserver/auth/controller/AuthController.java
  src/main/java/org/crops/fitserver/auth/facade/AuthFacade.java
  src/main/java/org/crops/fitserver/auth/facade/dto/SocialLoginPageResponse.java
  src/main/java/org/crops/fitserver/auth/facade/dto/TokenResponse.java
  src/main/java/org/crops/fitserver/auth/facade/impl/AuthFacadeImpl.java
  src/main/java/org/crops/fitserver/auth/service/OAuthService.java
  src/main/java/org/crops/fitserver/auth/service/impl/GoogleOAuthServiceImpl.java
  src/main/java/org/crops/fitserver/auth/service/impl/KakaoOAuthServiceImpl.java
  src/main/java/org/crops/fitserver/auth/service/provider/OAuthServiceProvider.java
  src/main/java/org/crops/fitserver/controller/SampleController.java
  src/main/java/org/crops/fitserver/global/config/SecurityConfig.java
  src/main/java/org/crops/fitserver/global/entity/BaseEntity.java
  src/main/java/org/crops/fitserver/global/entity/BaseTimeEntity.java
  src/main/java/org/crops/fitserver/global/exception/BusinessException.java
  src/main/java/org/crops/fitserver/global/exception/BusinessExceptionHandler.java
  src/main/java/org/crops/fitserver/global/exception/ErrorCode.java
  src/main/java/org/crops/fitserver/global/exception/ErrorResponse.java
  src/main/java/org/crops/fitserver/global/exception/FitException.java
  src/main/java/org/crops/fitserver/global/exception/NotFoundException.java
  src/main/java/org/crops/fitserver/global/exception/UnauthorizedException.java
  src/main/java/org/crops/fitserver/global/feign/oauth/OAuthToken.java
  src/main/java/org/crops/fitserver/global/feign/oauth/google/GoogleAuthServerClient.java
  src/main/java/org/crops/fitserver/global/feign/oauth/google/GoogleClientProperty.java
  src/main/java/org/crops/fitserver/global/feign/oauth/google/GoogleServerClient.java
  src/main/java/org/crops/fitserver/global/feign/oauth/google/GoogleSocialUserProfile.java
  src/main/java/org/crops/fitserver/global/feign/oauth/kakao/KakaoAuthServerClient.java
  src/main/java/org/crops/fitserver/global/feign/oauth/kakao/KakaoClientProperty.java
  src/main/java/org/crops/fitserver/global/feign/oauth/kakao/KakaoServerClient.java
  src/main/java/org/crops/fitserver/global/feign/oauth/kakao/KakaoSocialUserProfile.java
  src/main/java/org/crops/fitserver/global/filter/JwtAccessDeniedHandler.java
  src/main/java/org/crops/fitserver/global/filter/JwtAuthenticationFilter.java
  src/main/java/org/crops/fitserver/global/filter/JwtExceptionFilter.java
  src/main/java/org/crops/fitserver/global/http/ErrorType.java
  src/main/java/org/crops/fitserver/global/http/FailResponse.java
  src/main/java/org/crops/fitserver/global/http/HeaderTokenExtractor.java
  src/main/java/org/crops/fitserver/global/http/HttpResponse.java
  src/main/java/org/crops/fitserver/global/http/SocailPlatformRequestConverter.java
  src/main/java/org/crops/fitserver/global/jwt/JwtProperty.java
  src/main/java/org/crops/fitserver/global/jwt/JwtProvider.java
  src/main/java/org/crops/fitserver/global/jwt/JwtResolver.java
  src/main/java/org/crops/fitserver/global/jwt/TokenCollection.java
  src/main/java/org/crops/fitserver/global/jwt/TokenInfo.java
  src/main/java/org/crops/fitserver/global/log/LogConfig.java
  src/main/java/org/crops/fitserver/global/log/LogFilter.java
  src/main/java/org/crops/fitserver/global/log/LogRequestFilter.java
  src/main/java/org/crops/fitserver/global/security/PrincipalDetails.java
  src/main/java/org/crops/fitserver/global/security/PrincipalDetailsService.java
  src/main/java/org/crops/fitserver/user/domain/SocialPlatform.java
  src/main/java/org/crops/fitserver/user/domain/SocialUserInfo.java
  src/main/java/org/crops/fitserver/user/domain/User.java
  src/main/java/org/crops/fitserver/user/domain/UserRole.java
  src/main/java/org/crops/fitserver/user/repository/SocialUserInfoRepository.java
  src/main/java/org/crops/fitserver/user/repository/UserRepository.java
  src/main/java/org/crops/fitserver/user/repository/UserRepositoryCustom.java
  src/test/java/org/crops/fitserver/FitServerApplicationTests.java
  src/test/java/org/crops/fitserver/controller/SampleControllerTest.java
Labels: bug
