Repository Team-Crops/fit-server, pull requests merged in 2024-02, with the labels that each got.

#28 [feat] 약관 동의 관련 로직 추가
  build.gradle
  src/main/java/org/crops/fitserver/domain/user/constant/PolicyType.java
  src/main/java/org/crops/fitserver/domain/user/controller/UserController.java
  src/main/java/org/crops/fitserver/domain/user/domain/UserInfoSkill.java
  src/main/java/org/crops/fitserver/domain/user/domain/UserPolicyAgreement.java
  src/main/java/org/crops/fitserver/domain/user/dto/PolicyAgreementDto.java
  src/main/java/org/crops/fitserver/domain/user/dto/request/UpdatePolicyAgreementRequest.java
  src/main/java/org/crops/fitserver/domain/user/dto/request/UpdateUserRequest.java
  src/main/java/org/crops/fitserver/domain/user/dto/response/GetPolicyAgreementResponse.java
  src/main/java/org/crops/fitserver/domain/user/dto/response/UpdatePolicyAgreementResponse.java
  src/main/java/org/crops/fitserver/domain/user/facade/UserFacade.java
  src/main/java/org/crops/fitserver/domain/user/facade/UserFacadeImpl.java
  src/main/java/org/crops/fitserver/domain/user/repository/UserPolicyAgreementRepository.java
  src/main/java/org/crops/fitserver/domain/user/service/UserService.java
  src/main/java/org/crops/fitserver/domain/user/service/UserServiceImpl.java
  src/main/java/org/crops/fitserver/global/annotation/CurrentUser.java
  src/main/java/org/crops/fitserver/global/annotation/CurrentUserId.java
  src/main/java/org/crops/fitserver/global/config/WebConfig.java
  src/main/java/org/crops/fitserver/global/exception/ErrorCode.java
  src/test/java/org/crops/fitserver/domain/region/repository/RegionRepositoryTest.java
  src/test/java/org/crops/fitserver/domain/school/repository/SchoolRepositoryTest.java
  src/test/java/org/crops/fitserver/domain/skillset/repository/PositionRepositoryTest.java
  src/test/java/org/crops/fitserver/domain/skillset/repository/SkillRepositoryTest.java
  src/test/java/org/crops/fitserver/domain/user/controller/UserControllerTest.java
  src/test/java/org/crops/fitserver/domain/user/repository/UserPolicyAgreementRepositoryTest.java
  src/test/java/org/crops/fitserver/domain/user/repository/UserRepositoryTest.java
  src/test/java/org/crops/fitserver/domain/user/service/UserServiceTest.java
Labels: feat

#27 [test, feat] auth,chat test code, add api docs
  deploy/docker/Dockerfile
  deploy/docker/docker-compose.was.yml
  deploy/scripts/stopServer.sh
  src/main/java/org/crops/fitserver/domain/auth/controller/AuthController.java
  src/main/java/org/crops/fitserver/domain/chat/controller/dto/response/TextMessageResponse.java
  src/main/java/org/crops/fitserver/global/exception/BusinessExceptionHandler.java
  src/main/java/org/crops/fitserver/global/exception/ErrorCode.java
  src/main/java/org/crops/fitserver/global/socket/service/SocketResponse.java
  src/test/java/org/crops/fitserver/domain/auth/controller/AuthControllerTest.java
  src/test/java/org/crops/fitserver/domain/auth/facade/impl/AuthFacadeImplTest.java
  src/test/java/org/crops/fitserver/domain/auth/service/provider/OAuthServiceProviderTest.java
  src/test/java/org/crops/fitserver/domain/common/MockMvcDocsTest.java
  src/test/java/org/crops/fitserver/domain/file/controller/FileControllerTest.java
  src/test/java/org/crops/fitserver/domain/region/controller/RegionControllerTest.java
  src/test/java/org/crops/fitserver/domain/school/controller/SchoolControllerTest.java
  src/test/java/org/crops/fitserver/domain/skillset/controller/SkillSetControllerTest.java
  src/test/java/org/crops/fitserver/domain/user/controller/UserControllerTest.java
Labels: feat, test

#29 [feat] oauth login 시 redirect uri 파라미터 제거
  build.gradle
  src/main/java/org/crops/fitserver/domain/auth/controller/AuthController.java
  src/main/java/org/crops/fitserver/domain/auth/facade/AuthFacade.java
  src/main/java/org/crops/fitserver/domain/auth/facade/impl/AuthFacadeImpl.java
  src/main/java/org/crops/fitserver/domain/auth/service/OAuthService.java
  src/main/java/org/crops/fitserver/domain/auth/service/impl/GoogleOAuthServiceImpl.java
  src/main/java/org/crops/fitserver/domain/auth/service/impl/KakaoOAuthServiceImpl.java
  src/main/java/org/crops/fitserver/global/feign/oauth/google/GoogleClientProperty.java
  src/main/java/org/crops/fitserver/global/feign/oauth/kakao/KakaoClientProperty.java
  src/test/java/org/crops/fitserver/domain/auth/controller/AuthControllerTest.java
  src/test/java/org/crops/fitserver/domain/auth/facade/impl/AuthFacadeImplTest.java
Labels: feat

#32 [FEAT] http patch 메서드를 사용하기 위한 설정 고도화
  build.gradle
  src/main/java/org/crops/fitserver/domain/file/constant/FileDomain.java
  src/main/java/org/crops/fitserver/domain/file/service/FileService.java
  src/main/java/org/crops/fitserver/domain/file/service/S3FileServiceImpl.java
  src/main/java/org/crops/fitserver/domain/skillset/controller/SkillSetController.java
  src/main/java/org/crops/fitserver/domain/skillset/domain/Position.java
  src/main/java/org/crops/fitserver/domain/skillset/dto/request/CreatePositionRequest.java
  src/main/java/org/crops/fitserver/domain/skillset/dto/request/UpdatePositionRequest.java
  src/main/java/org/crops/fitserver/domain/skillset/dto/request/UpdateSkillRequest.java
  src/main/java/org/crops/fitserver/domain/skillset/service/SkillSetService.java
  src/main/java/org/crops/fitserver/domain/skillset/service/SkillSetServiceImpl.java
  src/main/java/org/crops/fitserver/domain/user/controller/UserController.java
  src/main/java/org/crops/fitserver/domain/user/domain/User.java
  src/main/java/org/crops/fitserver/domain/user/domain/UserInfo.java
  src/main/java/org/crops/fitserver/domain/user/dto/request/UpdateUserRequest.java
  src/main/java/org/crops/fitserver/domain/user/service/UserServiceImpl.java
  src/main/java/org/crops/fitserver/global/config/ObjectMapperConfig.java
  src/test/java/org/crops/fitserver/domain/auth/controller/AuthControllerTest.java
  src/test/java/org/crops/fitserver/domain/file/controller/FileControllerTest.java
  src/test/java/org/crops/fitserver/domain/region/controller/RegionControllerTest.java
  src/test/java/org/crops/fitserver/domain/school/controller/SchoolControllerTest.java
  src/test/java/org/crops/fitserver/domain/skillset/controller/SkillSetControllerTest.java
  src/test/java/org/crops/fitserver/domain/skillset/repository/PositionRepositoryTest.java
  src/test/java/org/crops/fitserver/domain/skillset/service/SkillSetServiceTest.java
  src/test/java/org/crops/fitserver/domain/user/controller/UserControllerTest.java
  src/test/java/org/crops/fitserver/domain/user/repository/UserRepositoryTest.java
  src/test/java/org/crops/fitserver/util/MockMvcDocs.java
  src/test/java/org/crops/fitserver/util/ObjectMapperTestConfig.java
Labels: enhancement
